Repository ccremer/kubernetes-zfs-provisioner, pull requests merged in 2022-07, with the labels that each got.

#69 Stop image push for quay.io
  .github/workflows/release.yml
  .goreleaser.yml
  Makefile.vars.mk
Labels: area:provisioner, kind:breaking

#71 Fix endpointleases in leader election
  go.mod
  go.sum
Labels: kind:bug, area:provisioner

#72 Allow RBAC permissions for leader election
  charts/kubernetes-zfs-provisioner/Chart.yaml
  charts/kubernetes-zfs-provisioner/README.md
  charts/kubernetes-zfs-provisioner/templates/rbac.yaml
Labels: kind:bug, chart:kubernetes-zfs-provisioner, area:chart

#73 Update helm instruction to use latest chart in Readme
  README.md
Labels: kind:documentation, area:provisioner
